### ISSUE TITLE
Touch event

### ISSUE THREAD

**Issue by 0x241F31** [weldonla/ARjs_Unity#1]
Hey, great project.!Could you please let me know could I somehow register click/pointermove/swipe event on object or screen?

**Comment by weldonla** [comment]
Currently I only have click events added. 

Select the object in question that you want to make into a button. Then click the "AR.js" menu item, and select "Make Button." You can then change the URL that the button links to in the inspector when the object is selected. NOTE: buttons don't work the best on mobile for some reason. You kinda need to tap the object many time in quick succession, but on the computer using the mouse it always gets it on just one click.

This is currently the only thing I have included in the plugin, but there are more things that are indeed possible. AR.js uses Aframe to handle 3d objects and interactions and such. If you want to dig around in the html and try adding something else, you can check out aframe's documentation. https://aframe.io/docs/1.0.0/introduction/interactions-and-controllers.html
