### ISSUE TITLE
Custom scripts for targeted objects.

### ISSUE THREAD

**Issue by Wolgraph** [weldonla/ARjs_Unity#3]
Hi.
I'm working on a web-based AR app where I procedurally create objects as the image marker is recognized. Then I can touch on these virtual objects and they do different things. 
Question is: does this workflow compile standard Unity C# scripts and make them work on web?

**Comment by weldonla** [comment]
No. Honestly, I wouldn't know how to get this plugin to do that haha. To do what you're wanting, you'll need to write in that functionality with javascript. If you compile files and check out the index.html file, there's a bunch of code between the <script> and </script> tags where you can add custom javascript functions.
