### ISSUE TITLE
Question : Build as self contained WebGL application

### ISSUE THREAD

**Issue by TomGreener91** [weldonla/ARjs_Unity#9]
Hi,
Was looking though the stuff thats done here and was wondering if there is a way to export as a self contained webgl application, rather than an export to go into an already existing site.

Im looking to build a web gl application that has a load of normal (non-ar) behaviour, but if you boot it up on a mobile device then you can enter/exit the AR mode.

Just wondering do you think this would be possiable?

**Comment by weldonla** [comment]
This plugin doesn't support that functionality. All this plugin really does is convert some specially made unity prefabs to html and javascript code. To do what you're looking to do, I would assume you would need to use Vuforia, build a typical AR application and export the app as a WebGL.
